### ISSUE TITLE
Error in deployment of synthetic-monitor with default performance thresholds

### ISSUE THREAD

**Issue by mdicss** [dynatrace-oss/dynatrace-monitoring-as-code#505] opened 2021-12-23 11:17 UTC
Hi
When I define a synthetic http monitor in the gui without defining performance thresholds (this is using the default values here), I can download it without problems. When trying to deploy it without changes, I get an error:

2021-12-23 12:03:05 ERROR       Failed to update DT object testcheck (HTTP 400)!
    Response was: {"error":{"code":400,"message":"No performance thresholds provided"}}, responsible config: projects/test/synthetic-monitor/testcheck.json

Probably the problem is on the donwload side or in the API.

Regards
Matthias

**Comment by UnseenWizzard** [comment] 2022-06-21 07:35
This will likely need similar behavior as the host-auto-update API which also returns less than is needed for uploading a configuration: (https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/issues/306). 
Open question: What exactly does the API expect on upload? Is an empty default possible, what's a sane default to set?

**Comment by Laubi** [comment] 2022-07-21 11:34
I was not able to reproduce the bug.
I created a synthetic HTTP monitor as described in the ticket without thresholds defined.
The downloaded config did not define it by default:
```{
 "anomalyDetection": {
  "loadingTimeThresholds": {
   "enabled": true,
   "thresholds": []   
  },
  ...
 ```

I was able to upload the config immediately again without any error. 
Thus, closing this ticket. Please reopen it if you're able to reproduce this issue.

**Closed by Laubi** 2022-07-21 11:34 UTC
Labels: bug, good first issue, area:download

**Comment by mdicss** [comment] 2022-07-21 13:02
I could no longer reproduce the problem. So it seems to be solved. :-)
