### ISSUE TITLE
Download current environment configuration

### ISSUE THREAD

**Issue by tatomir146** [dynatrace-oss/dynatrace-monitoring-as-code#19] opened 2020-10-07 10:53 UTC
For initial work with Dynatrace Monitoring as Code, customers would like to be able to download all the current configuration into a project structure.

For example, when running MaC with a flag (e.g.: download), all the supported configurations are downloaded and stored in a new project folder with the entire structure in place, as well as an initial .yaml file to apply. Optionally, the user can specify a list of configuration types that they want to download (e.g.: if they only want management-zones and auto-tag). 

This will help existing customers to get started with MaC and start migrating their existing config over.

**Comment by patrickpichler** [comment] 2020-11-16 07:13
Wouldn't it make more sense to remodel the cli to feature commands instead of just flags? 
Otherwise we would need to explicitly handle that only a certain number of flags is active, as 
some of those flags are mutually exclusive.

So instead of `monaco -d` it should be `monaco dry-run`. 
For download it should probably look like `monaco download`.

**Comment by UnseenWizzard** [comment] 2020-11-16 07:26
Yeah, as mentioned somewhere all flags that would fit a download are used already. 
I personally still like the idea of a second executable for this, mainly to call it 'cheese' but also to not bloat monaco/main even more.

Changing invocation to something like `monaco upload` & `monaco download` would work as well, but I find it strange that some of the flags will be the same, some will differ between those two invocations. then again that's probably normal. 

`--dry-run` I'd actually argue is a valid option that either commands should have. I might want to see how many configs I hit, before I pull them to my file system - e.g. when making the possibly bad choice to download everything from a big environment.

**Comment by patrickpichler** [comment] 2020-11-16 07:33
To be honest we could easily refactor the current functionality of main out as its own command and only to the args parsing/deciding what to call in main. That way one could even reuse single commands in other code projects
if needed.

As for the second binary, I'm do not quite like this to be honest. I don't want to remember the name of two tools ^^

**Comment by IgnacioGoldman** [comment] 2020-11-16 15:57
Hi,

I have created another tool that works in a similar way of the Monitoring as Code, configurations in a single yaml file, but it’s able to pull configurations from tenants.

How it works? 
1. An initial configuration is required to pass the tenants, tokens, configuration endpoints to touch. (The other 3 are to make the tool useful for Managed customers via MC)
![image](https://user-images.githubusercontent.com/11818563/99275369-b2004900-282b-11eb-98c3-1b05f3a10bbc.png)
2. Execute the python and pull the configuration from the tenants. The configuration will be stored in JSON and the tool will create yamls for each tenant, to easily move the configuration between them:
![image](https://user-images.githubusercontent.com/11818563/99275432-c6444600-282b-11eb-8d10-937757cd985b.png)
3.Then it’s just a matter of copying and pasting configuration from one tenant to the other in case we need to create or edit a specific configuration. Let’s suppose that a new tag with many rules is created in the tenant xxu26128. The rule will be visible under the respective yaml file and can be moved to the remaining tenants. This is how a config yaml file looks like:
![image](https://user-images.githubusercontent.com/11818563/99275470-d2c89e80-282b-11eb-8882-9139a9f5b110.png)


I would like to include this functionality within MaC but i feel it will deviate in the way you're thinking the project:
- It doesn't work with a JSON model and a YAML config file (such as MaC). The .yaml contains the full configuration (i'll start applying filters to reduce the lines of config)
- The structure of the directories are different. I find mine really useful since i just go wherever i want to propagate the configuration, i open all the files and with a copy and paste it's solved
- Written in Python (not a problem but still another point to work in)

Not sure if i'm commenting this thread in the right way and i hope i can help 👍 
here's the link to my MaC version: https://github.com/IgnacioGoldman/Dynatrace/tree/master/saveConfigAPI

**Comment by UnseenWizzard** [comment] 2020-11-16 16:32
Hi @IgnacioGoldman, 
thanks for reaching out, I'm excited for your contribution!

Is your https://github.com/IgnacioGoldman/Dynatrace private though? 
I get a 404 on that link :( 

From what you describe the structure does sound very different indeed. 
Our tool was designed around the idea to have one set of configuration, that can be modified for each environment via templating. 

One file per environment which is copy pasted seems somewhat error prone and a lot of effort once you go past a handful of environments?

**Comment by IgnacioGoldman** [comment] 2020-11-17 06:32
Hi Nico,

Yes indeed, it's private but i just sent you an invitation.

Just to clarify, it's one file per environment depending on the confiugration. For example, if yo want to propagate auto-tags in 4 different environemtns then you have 4 files, one for each. Then for Managemetn Zones, the files will be different. The yamls turn out more complex, i agree with you, but i see my approach faster and more flexible since the yamls are not dependant with the JSONs (you don't need to provide the structure with the JSON), so moving configuration between tenants is faster. 

I have been using monaco for automatically create alerting profiles and notification systems and it works well. But when it comes to tags or configurations that contains many rules, then it will become complex by itself.

Coming back to my solution, i was going to start creating filters to reduce the information to display in the yamls. Then my approach would reduce the complexity.

**Comment by JACONDE** [comment] 2020-11-20 12:52
Can I get an invitation as well to your project @IgnacioGoldman ?

**Comment by IgnacioGoldman** [comment] 2020-11-20 14:40
I sent an invitation to "JACONDE" if that's correct

**Comment by JACONDE** [comment] 2020-11-20 15:05
Just received. Thank you !

**Comment by kristofre** [comment] 2020-11-30 08:49
@JACONDE @IgnacioGoldman we are picking up this issue and will be developing an "Environment Download" solution that will look like this for a first release.

Monaco should be able to:

1. Have a flag to allow downloading all configurations of a tenant (e.g.: -download or something)
2. Create the folder structure in a folder that is specified in the command line (as a subfolder of the projects directory), e.g.: -dt=mytenantname
3. Iterate through all the configurations and
    b. Download all the JSONs into individual files
    c. Create 1 YAML file that contains a list of all configurations and their matching JSONs
    d. Follow dependencies and replace them with Monaco references (this capability should be able to be turned off with a flag, e.g. -no-dependencies

**Comment by JACONDE** [comment] 2020-11-30 08:58
That will be very good @kristofre . Do you have any ETA by when this new feature will be avaialble?

**Comment by IgnacioGoldman** [comment] 2020-11-30 09:39
Great to hear that @kristofre, let me know if i can help with anything else.

**Comment by kristofre** [comment] 2020-11-30 12:36
> That will be very good @kristofre . Do you have any ETA by when this new feature will be avaialble?

@JACONDE development work will start this or next week with a PR targeted for the end of the calendar year or beginning of next

**Comment by diegorqc** [comment] 2020-12-03 14:30
I'll take care of the implementation

**Comment by patrickpichler** [comment] 2021-02-01 12:19
I guess we can close this issue, or is still something missing? 
@didiladi @UnseenWizzard @diegorqc

**Comment by didiladi** [comment] 2021-02-01 12:54
I would really like to see an integration test for the functionality before closing this one. :rocket:

**Comment by UnseenWizzard** [comment] 2022-02-26 22:06
download feature exists for a while, further automated tests covered in  #423 -> closing

**Closed by UnseenWizzard** 2022-02-26 22:06 UTC
Labels: bug, enhancement
