### ISSUE TITLE
Cannot handle replaying configuration when CSM already exists

### ISSUE THREAD

**Issue by 163a** [dynatrace-oss/dynatrace-monitoring-as-code#124] opened 2021-01-20 22:43 UTC
Monaco cannot handle replaying configuration when calcuated service metric (CSM) already exists.

Monaco returns `ERROR Deployment to {env} failed with error Failed to upsert DT object {metric-name} (HTTP 400)!`

```
Response was: {"error":{"code":400,"message":"Constraints violated.","constraintViolations":[{"path":"id","message":"metricKey in payload, if given, must match metricKey in URL","parameterLocation":"PAYLOAD_BODY","location":null},{"path":"name","message":"Metric name already used","parameterLocation":"PAYLOAD_BODY","location":null}]}}, responsible config:
...
```

JSON
```
{
  "tsmMetricKey": "{{ .metric_key }}",
  "name": "{{ .name }}",
  "enabled": {{ .enabled }},
  "metricDefinition": {
    "metric": "{{ .metric_type }}",
    "requestAttribute": null
  },
  "unit": "{{ .metric_unit }}",
  "unitDisplayName": null,
  "entityId": null,
  "managementZones": [],
  "conditions": [
    {
      "attribute": "SERVICE_TYPE",
      "comparisonInfo": {
        "type": "SERVICE_TYPE",
        "comparison": "EQUALS",
        "value": "WEB_REQUEST_SERVICE",
        "negate": false
      }
    },
    {
      "attribute": "SERVICE_REQUEST_ATTRIBUTE",
      "comparisonInfo": {
        "type": "STRING_REQUEST_ATTRIBUTE",
        "comparison": "{{ .match_operator }}",
        "value": null,
        "negate": false,
        "requestAttribute": "{{ .request_attribute }}",
        "caseSensitive": false,
        "matchOnChildCalls": false,
        "source": null
      }
    }
  ],
  "dimensionDefinition": {
    "name": "Dimension",
    "dimension": "{Request:Name} (HTTP Method={HTTP-Method}, Status={HTTP-Status})",
    "placeholders": [],
    "topX": 100,
    "topXDirection": "DESCENDING",
    "topXAggregation": "{{ .metric_topx_aggregation }}"
  }
}
```

YAML
```
config:
  - mymetric_request_count: "request_single_attribute.json"
  - mymetric_response_time: "request_single_attribute.json"

mymetric_request_count:
  - name: "My Req Attr Request Count"
  - enabled: "true"
  - request_attribute: "My Req Attr"
  - match_operator: "EXISTS"
  - metric_key: "calc:service.mymetric.request.count"
  - metric_type: "REQUEST_COUNT"
  - metric_unit: "COUNT"
  - metric_topx_aggregation: "SINGLE_VALUE"

mymetric_response_time:
  - name: "My Req Attr Response Time"
  - enabled: "true"
  - request_attribute: "My Req Attr"
  - match_operator: "EXISTS"
  - metric_key: "calc:service.mymetric.response.time"
  - metric_type: "RESPONSE_TIME"
  - metric_unit: "MICRO_SECOND"
  - metric_topx_aggregation: "AVERAGE"
```

**Comment by mtrin-wooliesx** [comment] 2021-11-19 02:33
Experiencing the same issue. Is this a bug or is there a workaround?

**Comment by UnseenWizzard** [comment] 2022-06-22 09:50
Hi @163a @mtrin-wooliesx sorry for the very late reaction on this. 

With the current 1.7 version and the latest version of Dynatrace I was not able to reproduce this issue with your provided config @163a. Can you confirm this is still an issue for you? 

Dynatrace currently does not let me create two metrics with the same name - but if this was possible in the past, having two configs with the same name but different metric keys might be the cause of this issue.
Can you confirm if that might be the case for the environment you had the issue in? 

Also when you say 'replay' do you mean this configuration is originally downloaded with?

--- 
_As part of cleaning up monaco's backlog, I will close this ticket as resolved if you don't let me know this is still an issue within the next 10 days._

**Comment by 163a** [comment] 2022-07-21 07:10
Hi @UnseenWizzard this is so long ago that I could not exactly remember.
I believe I could try to re-produce it, and see if it is still an issue. But I would no longer have the same environment as before. I could try a new one.

**Comment by UnseenWizzard** [comment] 2022-07-21 09:10
Thanks for the reply @163a. 
For now I would assume this is not an issue anymore in the latest version of Dynatrace. 
If this does show up again please let us know - the upcoming 1.8.0 version also contains explicit handling on download and upload of configurations that are know to allow duplicate names. If this does happen again custom services can be handled as such an API

**Closed by UnseenWizzard** 2022-07-21 09:10 UTC
Labels: area:rest, support
