### ISSUE TITLE
Referencing other configurations does not work

### ISSUE THREAD

**Issue by edvorkin** [dynatrace-oss/dynatrace-monitoring-as-code#578] opened 2022-03-18 14:37 UTC
I am following the instruction for referencing other configurations but getting error creating a variable. 
```
Could not create configmanagementZoneId: loading config lifion-nonprod/managementZoneId failed with open ./lifion-nonprod/management-zone/zone-lifion.id: no such file or directory
```
I tried different combinations but no avail. 
Here are my configurations:
environments.yaml file in main directory:
nonprod:

```
    - name: "nonprod"
    - env-url: "{{ .Env.DT_BASEURL }}"
    - env-token-name: "DT_API_TOKEN"
lifion-nonprod:
    - name: "lifion-nonprod"
    - env-url: "{{ .Env.DT_BASEURL }}"
    - env-token-name: "DT_API_TOKEN"
```
   
Directory structure:
-lifion-nonprod
--- alerting-profile
--- management-zone

File in alerting profile that having error: alerting-profile.yaml
Content:
```
- managementZoneId: "/lifion-nonprod/management-zone/zone-lifion.id"
```
Management-zone directory has management-zone.yaml and zone.json.
Content of the  management-zone.yaml :
```
config:
- zone-lifion: zone.json
zone-lifion:
- name: '[Kubernetes] lifion-int-use1'

```

I am executing a command from the root directory:

```
monaco -e=environments.yaml --dry-run  -p=lifion-nonprod  --verbose
You are currently using the old CLI structure which will be used by
default until monaco version 2.0.0

Check out the beta of the new CLI by adding the environment variable
  "NEW_CLI".

We can't wait for your feedback.

2022-03-18 10:26:14 DEBUG request log not activated
2022-03-18 10:26:14 DEBUG response log not activated
2022-03-18 10:26:14 INFO  Dynatrace Monitoring as Code v1.7.0
2022-03-18 10:26:14 DEBUG Reading projects...
2022-03-18 10:26:14 DEBUG   project - lifion-nonprod
2022-03-18 10:26:14 DEBUG Processing file: lifion-nonprod/alerting-profile/alerting-profile.yaml
2022-03-18 10:26:14 ERROR Could not create configmanagementZoneId: loading config lifion-nonprod/managementZoneId failed with open ./lifion-nonprod/management-zone/zone-lifion.id: no such file or directory
2022-03-18 10:26:14 FATAL Loading of projects failed: loading config lifion-nonprod/managementZoneId failed with open ./lifion-nonprod/management-zone/zone-lifion.id: no such file or directory
```

**Comment by UnseenWizzard** [comment] 2022-06-21 07:12
Hi @edvorkin, sorry for the very late reply on this! 

The reference generally looks good. 
However is `- managementZoneId: "/lifion-nonprod/management-zone/zone-lifion.id"` all that's in your alerting-profile.yaml? 
It looks like monaco is trying to read as a config file "/lifion-nonprod/management-zone/zone-lifion.id" rather than resolving as a reference. 

Your altering profile yaml should look similar to the management-zone one, something like: 
```
config:
- some-alerting-profile: the-file-in-which-the-mgmt-zone-is-referenced.json
some-alerting-profile:
- name: 'This is some altering profile'
- managementZoneId: "/lifion-nonprod/management-zone/zone-lifion.id"
```

Could you please provide a minimal configuration in which to reproduce this issue (take yours and strip anything else/anything with internal details)? Thanks!

**Closed** 2022-11-23 15:30 UTC
Labels: support
